## ref
# https://medium.com/profusion-engineering/providing-an-equal-development-environment-with-docker-for-all-developers-99ee1d013a31

services:
  web:
    container_name: wquote-web
    image: node:18
    expose:
      - 4200
    ports:
      - 4201:4200
    volumes:
      - ../frontend:/opt/
    working_dir: /opt
    command: /bin/sh -c "npm install -g npm && npm install -g @angular/cli && bash"
    stdin_open: true # equivalent of docker -i
    tty: true        # equivalent of docker -t
    depends_on: 
      - api
      - database

  api:
    container_name: wquote-api
    image: python:3.11
    ports:
      - 8001:8000
    volumes:
      - ../backend:/opt
    working_dir: /opt
    command: /bin/sh -c "pip install --upgrade pip && pip install -r requirements.txt && tail -f /dev/null"
    stdin_open: true # equivalent of docker -i
    tty: true        # equivalent of docker -t

  nestjs:
    container_name: wquote-nestjs
    image: node:18
    ports:
      - 3000:3000
    volumes:
      - ../backend.nestjs:/opt/app
    working_dir: /opt/app
    command: /bin/sh -c "npm install -g npm && npm install && bash"
    stdin_open: true # equivalent of docker -i
    tty: true        # equivalent of docker -t


  database:
    container_name: wquote-db
    image: mongo:6.0.8
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db
      - dbconfig:/data/configdb
    # command: /bin/sh -c "npm install -g npm@latest && npm install && bash"
    stdin_open: true # equivalent of docker -i
    tty: true        # equivalent of docker -t


volumes:
  dbdata:
  dbconfig:
