## ref
# https://medium.com/profusion-engineering/providing-an-equal-development-environment-with-docker-for-all-developers-99ee1d013a31

services:
  web:
    container_name: wquote-devenv-web
    build: 
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - frontend
    depends_on: 
      - api

  api:
    container_name: wquote-devenv-api
    build:
      context: ../backend
      dockerfile: Dockerfile
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
